title: AppBuilder Documentation
description: Comprehensive documentation for the AppBuilder platform, including guides, concepts, API references, and tutorials.
theme: just-the-docs

url: https://your-appbuilder-docs-site-url.com

# Optionally update or remove aux_links
# aux_links:
#   AppBuilder Documentation Repository: https://github.com/your-org/appbuilder-docs
